#!/bin/bash

echo 'gene name, gene length, number of benign labels, number of pathogenic labels, number of LOF labels, number of GOF labels, number of labeled variants, LLR ROC-AUC, LLR-KNN ROC-AUC, ESM kNN Clinvar ROC-AUC, ESM kNN LOF-GOF ROC-AUC, ESM Gaussian NB Clinvar ROC-AUC, ESM Gaussian NB LOF-GOF ROC-AUC, ESM Random Forest Clinvar ROC-AUC, ESM Random Forest LOF-GOF ROC-AUC, ESM Logistic Regression Clinvar ROC-AUC, ESM Logistic Regression LOF-GOF ROC-AUC, VAE kNN Clinvar ROC-AUC, VAE kNN LOF-GOF ROC-AUC, UMAP kNN Clinvar ROC-AUC, UMAP kNN LOF-GOF ROC-AUC' > output.csv
#grep -E 'gene name|gene length|GOF labels|Pathogenic labels|LOF labels|Benign labels|number of labeled variants|LLR ROC-AUC|ESM Clinvar ROC-AUC|ESM LOF-GOF ROC-AUC|VAE Clinvar ROC-AUC|VAE LOF-GOF ROC-AUC|UMAP Clinvar ROC-AUC|UMAP LOF-GOF ROC-AUC' output.txt | awk 'BEGIN {FS = ": "}; {sub(/^[[:blank:]]*/, "", $1); sub(/[[:blank:]]*$/, "", $2); arr[$1] = $2}; END {print arr["gene name"] "," arr["gene length"] "," arr["GOF labels"] "," arr["Pathogenic labels"] "," arr["LOF labels"] "," arr["Benign labels"] "," arr["number of labeled variants"] "," arr["LLR ROC-AUC"] "," arr["ESM Clinvar ROC-AUC"] "," arr["ESM LOF-GOF ROC-AUC"] "," arr["VAE Clinvar ROC-AUC"] "," arr["VAE LOF-GOF ROC-AUC"] "," arr["UMAP Clinvar ROC-AUC"] "," arr["UMAP LOF-GOF ROC-AUC"]}' >> output.csv


# Process the input file and append data to the CSV
#awk -F ':' 'BEGIN { OFS="," } NF>1 { print $2 }' output.txt | xargs -n21 >> output.csv
awk -F ':' 'BEGIN { OFS="," } NF>1 { printf("%s%s",sep,$2); sep="," } END { print "" }' output.txt | xargs -n21 >> output.csv
#awk -F ':' '{ if (NF > 1) { printf "%s,", $2 } else { printf "," } } END { print "" }' output.txt >> output.csv
#echo "" >> output.csv
#echo 'gene name, gene length, number of GOF labels, number of pathogenic labels, number of LOF labels, number of Benign labels,number of labeled variants,LLR ROC-AUC,LLR-KNN ROC-AUC, ESM Clinvar ROC-AUC,ESM LOF-GOF ROC-AUC,VAE Clinvar ROC-AUC,VAE LOF-GOF ROC-AUC,UMAP Clinvar ROC-AUC,UMAP LOF-GOF ROC-AUC' > output.csv
#grep -E 'gene name|gene length|Benign labels|Pathogenic labels|LOF labels|GOF labels|labeled variants|LLR ROC-AUC|LRR-KNN ROC-AUC|ESM kNN Clinvar ROC-AUCC|ESM kNN LOF-GOF ROC-AUC|ESM Gaussian NB Clinvar ROC-AUC|ESM Gaussian NB LOF-GOF ROC-AUC|ESM Random Forest Clinvar ROC-AUC|ESM Random Forest LOF-GOF ROC-AUC|ESM Logistic Regression Clinvar ROC-AUC|ESM Logistic Regression LOF-GOF ROC-AUC|VAE kNN Clinvar ROC-AUC|VAE kNN LOF-GOF ROC-AUC|UMAP kNN Clinvar ROC-AUC|UMAP kNN LOF-GOF RROC-AUC' output.txt | awk 'BEGIN {FS = ": "} {print $2}' | paste -d "," - - - - - - - - - - - - - - - - - - - - - >> output.csv
